# CI de nivel 01 - Disparo manual a partir de 1 clique

name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  testes-unitarios:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando dependencias
        run: npm install

      - name: Instalando Mocha
        run: npm install -D mocha

      - name: Executando os testes unitários
        run: npx mocha testes/trabalho-final.js
      
      - name: Gerar relatório JUnit
        run: npm run test:junit
        
      - name: Carregar relatório de testes
        uses: actions/upload-artifact@v2
        with:
          name: mocha-junit-report
          path: ./test-results/junit.xml
